### ISSUE TITLE
Compile Error, "Extra argument 'showsIndicators' in call" in  ScrollView(showsIndicators: false) 

### ISSUE THREAD

**Issue by AmrAbedal** [Q-Mobile/QGrid#1]

**Comment by karolkulesza** [comment]
Hi Amr,
Are you using the latest Xcode 11 beta? (beta 4 11M374r, as indicated in Readme). `ScrollView` initializer with `showsIndicators` argument is available, as documented here: [https://developer.apple.com/documentation/swiftui/scrollview/3337759-init](https://developer.apple.com/documentation/swiftui/scrollview/3337759-init)

**Comment by AmrAbedal** [comment]
Hi Karol, 
thanks I will update my Xcode to this version,  as my current version is  ( 11M336w )

**Comment by karolkulesza** [comment]
Great, closing, then.
