### ISSUE TITLE
Safe Area causing some problems when contained in a NavigationView

### ISSUE THREAD

**Issue by andreas-braun-parship** [Q-Mobile/QGrid#14]
I noticed that the QGrid only works well when not contained in a NavigationView.

It seems to not correctly respect the safe area and cuts off part of the UI that seem to have the hight of the navigation bar.

Here are some examples of what I mean:

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-22 at 11 22 03](https://user-images.githubusercontent.com/49232993/67273155-32843700-f4be-11e9-9504-af0ed49e93cd.png)

As you can see part of the UI underneath the navigation bar is cut out.
Also the lower part of the grid is cut out due to the home indicator.

```
NavigationView {
    QGrid(profiles, columns: 2) { profile in
        ProfileCardView(profile: profile)
    }
}
```

If I add the `.edgesIgnoringSafeArea([.all])` to the grid, this is what happens:

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-22 at 11 24 24](https://user-images.githubusercontent.com/49232993/67273346-8b53cf80-f4be-11e9-827c-5cb3f002b72b.png)

```
NavigationView {
    QGrid(profiles, columns: 2) { profile in
        ProfileCardView(profile: profile)
    }
    .edgesIgnoringSafeArea(.all)
}
```

**Comment by karolkulesza** [comment]
Thanks for the feedback.

By default, QGrid specifies non-zero values for its `vPadding` and `hPadding` parameters. Specifying no padding (`vPadding: 0`) in this precise use case should address this issue. (It's not related to safe areas)
