### ISSUE TITLE
Demo of QGridTestApp problem

### ISSUE THREAD

**Issue by writing-shed** [Q-Mobile/QGrid#20]
If you embed the ZStack in a List as in the following:

    var body: some View {
        GeometryReader { geometry in
            List {
                ZStack {
                    self.backgroundGradient
                        .edgesIgnoringSafeArea(.all)
                    VStack {
                        if (QConstants.showDesigner) { self.designerView(geometry) }
                        self.gridView(geometry)
                    }
                }
            }
        }
    }

Then you get this in the simulator:

<img width="584" alt="Screenshot 2019-11-12 at 12 42 31" src="https://user-images.githubusercontent.com/25199371/68672912-8bd60800-054a-11ea-8204-fcf4cc8f8313.png">

I have tried various experiments and the best I can come up with is to add a frame modifier as in:

    var body: some View {
        GeometryReader { geometry in
            List {
                ZStack {
                    self.backgroundGradient
                        .edgesIgnoringSafeArea(.all)
                    VStack {
                        if (QConstants.showDesigner) { self.designerView(geometry) }
                        self.gridView(geometry)
                        .frame(width: geometry.size.width,
                               height: geometry.size.height)
                    }
                }
            }
        }
    }

But this is still wrong because the grid is in the wrong place (see screenshot) and I can't work out how to fix it. Any ideas?

<img width="584" alt="Screenshot 2019-11-12 at 12 50 06" src="https://user-images.githubusercontent.com/25199371/68673235-246c8800-054b-11ea-8a09-4f2779cd3b0a.png">

**Comment by karolkulesza** [comment]
Hi there,

`ZStack` is used here just for specifying the background gradient, so if you'd like to embed the content in a List view, you should rather do something like this:

```
  var body: some View {
    GeometryReader { geometry in
      ZStack {
        self.backgroundGradient
        .edgesIgnoringSafeArea(.all)
        List {
          self.gridView(geometry)
            .frame(height: geometry.size.height)
        }
      }
    }
  }
```

This assumes that you'd like the grid to occupy the whole screen. (in case of embedding it in a `List` you have to explicitly set `QGrid`'s height.
Not sure, however, what is your purpose of embedding it in a List, especially that there might be a conflict of vertical scrolling gestures in such case (embedding `QGrid` in a `List`)
