### ISSUE TITLE
QGrid NavigationView scroll layout issue

### ISSUE THREAD

**Issue by jacobcxdev** [Q-Mobile/QGrid#21]
When you scroll there is a layout issue at the top of the screen. The GIF below compares expected and actual behaviour.

[QGrid Bug](https://gist.github.com/jacobcxdev/29f41f1e5cb11ecfb78aa9980c625503)

**Comment by jacobcxdev** [comment]
Commenting [these lines](https://github.com/Q-Mobile/QGrid/blob/40607aec336a8097c94bcadb81762592d89073ac/Sources/QGrid/QGrid.swift#L113-L114) fixes it.

**Comment by karolkulesza** [comment]
Thanks for the feedback.

By default, QGrid specifies non-zero values for  its `vPadding` and `hPadding` parameters. Specifying no padding (`vPadding: 0`) in this precise use case addresses this issue.
