### ISSUE TITLE
Not Lazy?

### ISSUE THREAD

**Issue by jeremyquinn** [Q-Mobile/QGrid#31]
Testing this in the simulator and every cell is generated on launch, not as you scroll (like SwiftUI List).

Or have I misunderstood something?

**Comment by saket** [comment]
I have the same question. I expected QGrid to lazy load the cells, as indicated in the readme:

> It uses the same approach as SwiftUI's List view, by computing its cells on demand from an underlying collection of identified data.

**Comment by karolkulesza** [comment]
You're right, I just updated readme / code comments.
`QGrid` is using `ForEach` under the hood, which does not seem to support lazy loading out of the box, so this is a good candidate for `QGrid`'s next release feature.
