### ISSUE TITLE
Grid with static cells

### ISSUE THREAD

**Issue by alelordelo** [Q-Mobile/QGrid#4]
Hi @karolkulesza, 

Amazing stuff mate, been waiting for this since SwiftUI was introduced! : )

Im trying to make a simple grid without data (static cells), but got the error bellow. Any idea what is wrong?

I am  using:
Xcode 11 Beta 5
Catalina Beta 5

<img width="1439" alt="Screenshot 2019-08-11 at 15 02 02" src="https://user-images.githubusercontent.com/17708751/62834207-73073f00-bc49-11e9-8d79-55a83876c0fa.png">

`//  GridView.swift

import QGrid
import SwiftUI

struct GridView: View {
  var body: some View {
    QGrid(columns: 4, { ProductCell() }
  }
}

#if DEBUG
struct GridView_Previews : PreviewProvider {
    static var previews: some View {
        GridView()
    }
}
#endif`

**Comment by karolkulesza** [comment]
Hi @alelordelo, 

As you can see in the Roadmap / TODOs section, this is one of the features that could be implemented, so if you want, feel free to contribute 😎

Best,
Karol
