### ISSUE TITLE
Error when importing QGrid in project with lower deployment target

### ISSUE THREAD

**Issue by rivera-ernesto** [Q-Mobile/QGrid#44]
I am trying to use QGrid on my iOS 10+ app with no luck.

>  Compiling for iOS 10.0, but module 'QGrid' has a minimum deployment target of iOS 13.0

I would like to import it and use it conditionally just like `import SwiftUI` does. Any ideas?

Thank you

**Comment by karolkulesza** [comment]
You can easily achieve that just by:

1. Changing `.iOS(.v13)` to `.iOS(.v10)` in QGrid’s `Package.swift`
2. Marking all the structs utilising QGrid with: `@available(iOS 13.0, *)` attribute

Hope that helps!

Best,
Karol

**Comment by rivera-ernesto** [comment]
I see, thank you.
Wondering what are the best (or "less bad") practices in this case.

**Comment by rivera-ernesto** [comment]
Would it make sense to add `@available(iOS 13.0, OSX 10.15, tvOS 13.0, watchOS 6.0, *)` where needed to ease manually adding the code to a project with a lower deployment target?
