### ISSUE TITLE
Use of unresolved identifier 'UIDevice'

### ISSUE THREAD

**Issue by melgu** [Q-Mobile/QGrid#5]
Upon adding the Swift Package, I get the compile time error `Use of unresolved identifier 'UIDevice'`even when not using the package yet.

The line throwing the error is
```
private var cols: Int {
    UIDevice.current.orientation.isLandscape ? columnsInLandscape : columns
}
```
in QGrid.swift.

Target is macOS Catalina.

**Comment by karolkulesza** [comment]
Hi @melgu 

Thanks for the feedback. macOS support is done via Mac Catalyst (see: https://developer.apple.com/documentation/uikit/creating_a_mac_version_of_your_ipad_app, https://developer.apple.com/ipad-apps-for-mac/). 

In other words, you should create iOS app project and enable the "Mac" checkbox in the project settings.

**Comment by melgu** [comment]
Thank for the clarification. You should probably mention that in the requirements.
