### ISSUE TITLE
MacOS build does not scroll

### ISSUE THREAD

**Issue by alancook** [Q-Mobile/QGrid#6]
MacOS build does not scroll works fine for IOS

**Comment by alancook** [comment]
Looks like this is a Apple bug in SwitIUI

**Comment by jhoughjr** [comment]
any ideas on a workaround?

**Comment by jhoughjr** [comment]
I can add that it does bounce vertically but doesn't scroll downward.

**Comment by jhoughjr** [comment]
in QGrid.swift by enabling the scroll indicators and making no other changes 
macOS version scrolls properly.
This would lead me to believe it is not an OS bug but some side effect.

`  public var body : some View {
    GeometryReader { geometry in
      ScrollView(showsIndicators: true) {
        VStack(spacing: self.vSpacing) {
          ForEach((0..<self.rows).map { QGridIndex(id: $0) }) { row in
            self.rowAtIndex(row.id * self.cols,
                            geometry: geometry)
          }
          // Handle last row
          if (self.data.count % self.cols > 0) {
            self.rowAtIndex(self.cols * self.rows,
                            geometry: geometry,
                            isLastRow: true)
          }
        }
      }
      .padding(.horizontal, self.hPadding)
      .padding(.vertical, self.vPadding)
    }
  }`

**Comment by nogginbox** [comment]
I'm having this issue too.

I don't understand @jhoughjr's suggestion. Are you wrapping QGrid in a scroll view? Or is that a suggested fix to the QGrid code?
