### ISSUE TITLE
Cocoapods support?

### ISSUE THREAD

**Issue by plivesey** [Q-Mobile/QGrid#9]
This library looks awesome, but probably not going to use it without cocoapods support. For me, it's probably not worth using two dependency managers in the same project (especially with SPM being such a new technology).

I totally understand if you don't want to support multiple dependency managers, but if you did, you'd probably get more traction, usage, and PRs.

**Comment by karolkulesza** [comment]
Hi there,

SwiftUI is equally new technology as SPM 😆
Feel free to contribute to this project by creating a PR, if you see there is any issue. I'm currently focused on QDesigner Beta (https://Q-Mobile.IT/Q-Designer).

Best,
Karol

**Comment by plivesey** [comment]
👍 true. And thanks. Good luck with q designer.

**Comment by fbartho** [comment]
As a counterpoint, while I'm thrilled that cocoapods existed in a time before SPM, I really think it has aged out. Cocoapods caused/causes so much maintenance and weirdness that I'd really prefer to avoid it in all my projects.

Anyhow, just putting a different thought out there -- not trying to start a flamewar!

**Comment by karolkulesza** [comment]
Closing, as this is not an issue, but a feature request (to be potentially implemented by the community in the future).
